"""Server-side handling of the end-to-end encryption public key."""

import base64
import json
from contextlib import contextmanager

import pytest

from utils.keys import validate_public_key

# Two real keys, generated by the browser's WebCrypto (see static/js/crypto.js).
KEY_A = "BEGErKUFiFI2+tzkTC8C80z0vw/Nji/LtStHrOKwtnESDdAjIyzfbxdzWOyw8tQQ3cJRGiehEBh3IBKZqZ+7wwQ="
KEY_B = "BHtBHRyJNoPmzR8b4ftX8h4w/wWMbc4u9ZDXxAKVNvGv+1nuUPQMMgi69j0Fa6I2G6SAytujh/lj0c0nmj5JZlE="
USER_ID = "11111111-1111-1111-1111-111111111111"


def _mutate(key_b64, index, xor):
    raw = bytearray(base64.b64decode(key_b64))
    raw[index] ^= xor
    return base64.b64encode(bytes(raw)).decode()


# --- the validator ----------------------------------------------------------------

def test_real_webcrypto_keys_are_accepted_unchanged():
    assert validate_public_key(KEY_A) == (KEY_A, None)
    assert validate_public_key("  " + KEY_B + "\n") == (KEY_B, None)      # whitespace is tolerated


def test_no_key_is_fine():
    assert validate_public_key(None) == (None, None)
    assert validate_public_key("") == (None, None)


@pytest.mark.parametrize("label, value", [
    ("a point that is not on the curve", _mutate(KEY_A, 64, 1)),
    ("a compressed key", base64.b64encode(bytes([2]) + base64.b64decode(KEY_A)[1:33]).decode()),
    ("the wrong prefix byte", _mutate(KEY_A, 0, 1)),
    ("a 32-byte private scalar", base64.b64encode(b"\x01" * 32).decode()),
    ("a private key as JSON (JWK)", json.dumps({"kty": "EC", "crv": "P-256", "x": "a", "y": "b", "d": "SECRET"})),
    ("a JSON array", "[1,2,3]"),
    ("not base64", "%%% not base64 %%%"),
    ("far too long", "A" * 5000),
    ("a number", 12345),
    ("a list", [KEY_A]),
    ("x = 0", base64.b64encode(bytes([4]) + bytes(32) + bytes(32)).decode()),
])
def test_bad_keys_are_rejected(label, value):
    key, error = validate_public_key(value)
    assert key is None and error, f"accepted {label}"


def test_private_key_material_is_refused_with_a_clear_reason():
    _, error = validate_public_key(json.dumps({"kty": "EC", "d": "x"}))
    assert "private key" in error.lower()


# --- routes -------------------------------------------------------------------------

class ScriptedCursor:
    def __init__(self, rows):
        self.rows, self.executed = list(rows), []

    def execute(self, sql, params=None):
        self.executed.append((" ".join(sql.split()), params))

    def fetchone(self):
        return self.rows.pop(0) if self.rows else None

    def fetchall(self):
        return self.rows


class FakeAuth:
    def __init__(self):
        self.sign_ups = 0

    def sign_up(self, email, password):
        self.sign_ups += 1
        return {"id": USER_ID, "identities": [{"id": USER_ID}]}

    def get_user(self, token):
        return {"id": USER_ID}


@pytest.fixture()
def wired(monkeypatch):
    """Patches Supabase Auth and the database; returns helpers plus every cursor that was opened."""
    state = {"cursors": [], "auth": FakeAuth(), "rows": []}

    @contextmanager
    def route_db(commit=False):
        cur = ScriptedCursor(state["rows"])
        state["cursors"].append(cur)
        yield cur

    @contextmanager
    def auth_db(commit=False):
        yield ScriptedCursor([{"id": USER_ID, "username": "alice", "role": "user", "status": "active"}])

    monkeypatch.setattr("routes.auth.get_supabase_auth", lambda: state["auth"])
    monkeypatch.setattr("routes.auth.db_cursor", route_db)
    monkeypatch.setattr("utils.auth_helpers.get_supabase_auth", lambda: state["auth"])
    monkeypatch.setattr("utils.auth_helpers.db_cursor", auth_db)
    return state


def _register(client, **extra):
    body = {"username": "alice", "email": "alice@example.com", "password": "secret1", **extra}
    return client.post("/api/auth/register", json=body)


def _inserts(state):
    return [(sql, params) for cur in state["cursors"] for sql, params in cur.executed if "INSERT INTO profiles" in sql]


def test_register_stores_the_public_key(client, wired):
    assert _register(client, public_key=KEY_A).status_code == 201
    (_, params), = _inserts(wired)
    assert KEY_A in params


def test_register_without_a_key_still_works(client, wired):
    assert _register(client).status_code == 201
    (_, params), = _inserts(wired)
    assert params[3] is None


def test_register_rejects_a_bad_key_before_creating_anything(client, wired):
    res = _register(client, public_key=json.dumps({"kty": "EC", "d": "SECRET"}))
    assert res.status_code == 400
    assert wired["auth"].sign_ups == 0          # no Supabase account was created
    assert not _inserts(wired)                  # and no profile row


def test_private_key_is_never_stored_even_if_a_client_sends_it(client, wired):
    private_scalar = base64.b64encode(b"\x07" * 32).decode()
    assert _register(client, public_key=private_scalar).status_code == 400
    assert not _inserts(wired)


def _put_key(client, value):
    return client.put("/api/auth/public-key", json={"public_key": value}, headers={"Authorization": "Bearer t"})


def test_a_user_can_set_their_own_key(client, wired):
    wired["rows"] = [{"id": USER_ID, "username": "alice", "public_key": KEY_B}]
    res = _put_key(client, KEY_B)
    assert res.status_code == 200 and res.get_json()["profile"]["public_key"] == KEY_B
    (sql, params), = [e for c in wired["cursors"] for e in c.executed if "UPDATE profiles" in e[0]]
    assert params == (KEY_B, USER_ID)                     # updates only the caller's own row


@pytest.mark.parametrize("value", [None, "", "garbage", _mutate(KEY_A, 64, 1)])
def test_setting_an_invalid_key_is_refused_and_writes_nothing(client, wired, value):
    assert _put_key(client, value).status_code == 400
    assert not [e for c in wired["cursors"] for e in c.executed if "UPDATE profiles" in e[0]]


def test_setting_a_key_requires_login(client, wired):
    assert client.put("/api/auth/public-key", json={"public_key": KEY_A}).status_code == 401


def test_conversation_participants_include_their_public_keys():
    from pathlib import Path
    source = (Path(__file__).resolve().parent.parent / "routes" / "conversations.py").read_text()
    assert "p.username, p.public_key" in source
